version: "3"

services:
  server:
    container_name: data-warn-bot
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      NODE_ENV: production
      DD_SITE: datadoghq.com
      DD_API_KEY: xxx
      DD_APP_KEY: xxx
